name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_pocketbase:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Preset Image Name
        run: echo "POCKETBASE_IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
  
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: './web' # https://github.com/docker/build-push-action/issues/169#issuecomment-711729397
          file: './web/Dockerfile'
          push: true
          tags: ${{ env.POCKETBASE_IMAGE_URL }}
  
      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://mike-caprover-pocketbase-demo.uk
          app: "pocketbase-manual"
          # server: "${{ secrets.CAPROVER_SERVER }}"
          # app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
    
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
  
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: './web' # https://github.com/docker/build-push-action/issues/169#issuecomment-711729397
          file: './web/Dockerfile'
          push: true
          tags: ${{ env.IMAGE_URL }}
  
      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://mike-caprover-pocketbase-demo.uk
          app: "sveltekit"
          # server: "${{ secrets.CAPROVER_SERVER }}"
          # app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     accessToken: ${{ github.token }}
      #     containerRegistry: true
      #     working-directory: web
      # - name: Deploy on CapRover
      #   uses: caprover/deploy-from-github@v1.1.2
      #   with:
      #     server: https://mike-caprover-pocketbase-demo.uk
      #     app: "sveltekit"
      #     token: "${{ secrets.APP_TOKEN }}"
      #     image: "ghcr.io/midanosi/mike-cck-mvp:latest"

